"""Jobs-owned records and validation for the unregistered draft task graph."""

from .admission import InitialTaskProposal
from .context import TaskContextBundle
from .guard import SQLiteTaskAttemptGuard
from .models import (
    AttemptBudgetReservation,
    AttemptState,
    BudgetAmount,
    BudgetLedger,
    BudgetLimit,
    ControlKind,
    ControlState,
    EdgeKind,
    GraphAdmission,
    GraphAuthority,
    GraphDesiredState,
    GraphEvent,
    GraphEventPage,
    GraphInspection,
    GraphJob,
    GraphJobSpecification,
    GraphLimits,
    GraphMutation,
    GraphMutationRequest,
    GraphState,
    GraphTask,
    GraphTaskSpecification,
    JobGraph,
    MutationDecision,
    TaskAttempt,
    TaskCheckpoint,
    TaskComment,
    TaskControl,
    TaskDependency,
    TaskExecutionKind,
    TaskResult,
    TaskRole,
    TaskState,
)
from .validation import (
    GraphValidationError,
    require_attempt_transition,
    require_graph_transition,
    require_task_transition,
    validate_graph_admission,
    validate_graph_topology,
    validate_mutation,
)

__all__ = [
    "AttemptBudgetReservation",
    "AttemptState",
    "BudgetAmount",
    "BudgetLedger",
    "BudgetLimit",
    "ControlKind",
    "ControlState",
    "EdgeKind",
    "GraphAdmission",
    "GraphAuthority",
    "GraphDesiredState",
    "GraphEvent",
    "GraphEventPage",
    "GraphInspection",
    "GraphJob",
    "GraphJobSpecification",
    "GraphLimits",
    "GraphMutation",
    "GraphMutationRequest",
    "GraphState",
    "GraphTask",
    "GraphTaskSpecification",
    "GraphValidationError",
    "JobGraph",
    "InitialTaskProposal",
    "MutationDecision",
    "TaskAttempt",
    "TaskCheckpoint",
    "TaskComment",
    "TaskContextBundle",
    "TaskControl",
    "TaskDependency",
    "TaskExecutionKind",
    "TaskResult",
    "TaskRole",
    "TaskState",
    "SQLiteTaskAttemptGuard",
    "require_attempt_transition",
    "require_graph_transition",
    "require_task_transition",
    "validate_graph_admission",
    "validate_graph_topology",
    "validate_mutation",
]
