"""
Shared runtime primitives for Daita runtimes and plugin extensions.
"""

from .primitives import (
    AccessMode,
    ApprovalRequest,
    ApprovalStatus,
    Capability,
    ContextAudience,
    ContextBlock,
    ContextProvider,
    Evidence,
    EvidenceSchema,
    Executor,
    GovernanceAuditRecord,
    GovernanceResult,
    Operation,
    OperationStatus,
    Policy,
    PolicyDecision,
    PolicyDecisionTrace,
    PolicyEffect,
    RiskLevel,
    RuntimeEvent,
    RuntimeEventType,
    RuntimeStore,
    Task,
    TaskDependency,
    TaskDependencyKind,
    TaskStatus,
    ToolView,
    Worker,
)
from .governance import PolicyEvaluator, evaluate_policies
from .approvals import InMemoryApprovalChannel
from .events import RuntimeStreamEvent
from .executors import EvidenceWrappingExecutor
from .kernel import (
    RuntimeFactProvider,
    RuntimeKernel,
    RuntimeKernelExecutionError,
    RuntimeKernelExecutorFailed,
    RuntimeKernelGovernanceBlocked,
    RuntimeKernelLeaseLost,
    RuntimeKernelTaskAlreadyTerminal,
    RuntimeKernelTaskNotRunnable,
    TaskExecutionResult,
    TaskLease,
)
from .tool_adapters import (
    LocalToolRuntimeAdapter,
    LocalToolRuntimeRegistration,
    local_tool_plugin_for,
    register_local_tool,
)
from .monitors import MonitorRuntime, MonitorSpec, MonitorState, MonitorTickResult
from .scheduler import OperationScheduleResult, OperationTaskScheduler
from .store import InMemoryRuntimeStore, OperationSnapshot
from .sqlite_store import SQLiteRuntimeStore
from .workers import (
    TaskHandoff,
    WorkerRunResult,
    WorkerRuntime,
    WorkerRuntimeOptions,
)

__all__ = [
    "AccessMode",
    "ApprovalRequest",
    "ApprovalStatus",
    "Capability",
    "ContextAudience",
    "ContextBlock",
    "ContextProvider",
    "Evidence",
    "EvidenceSchema",
    "EvidenceWrappingExecutor",
    "Executor",
    "GovernanceAuditRecord",
    "GovernanceResult",
    "Operation",
    "OperationStatus",
    "OperationSnapshot",
    "Policy",
    "PolicyDecision",
    "PolicyDecisionTrace",
    "PolicyEffect",
    "PolicyEvaluator",
    "RiskLevel",
    "RuntimeEvent",
    "RuntimeEventType",
    "RuntimeFactProvider",
    "RuntimeKernel",
    "RuntimeKernelExecutionError",
    "RuntimeKernelExecutorFailed",
    "RuntimeKernelGovernanceBlocked",
    "RuntimeKernelLeaseLost",
    "RuntimeKernelTaskAlreadyTerminal",
    "RuntimeKernelTaskNotRunnable",
    "RuntimeStore",
    "RuntimeStreamEvent",
    "LocalToolRuntimeAdapter",
    "LocalToolRuntimeRegistration",
    "InMemoryApprovalChannel",
    "InMemoryRuntimeStore",
    "MonitorRuntime",
    "MonitorSpec",
    "MonitorState",
    "MonitorTickResult",
    "OperationScheduleResult",
    "SQLiteRuntimeStore",
    "OperationTaskScheduler",
    "Task",
    "TaskDependency",
    "TaskDependencyKind",
    "TaskHandoff",
    "TaskExecutionResult",
    "TaskLease",
    "TaskStatus",
    "ToolView",
    "Worker",
    "WorkerRunResult",
    "WorkerRuntime",
    "WorkerRuntimeOptions",
    "evaluate_policies",
    "local_tool_plugin_for",
    "register_local_tool",
]
