"""Provider-neutral model contracts."""

from .errors import ModelProviderError, ProviderErrorCode
from .factory import create_llm_provider, create_model_route_provider
from .models import (
    CanonicalMessage,
    FinishReason,
    MessageRole,
    ModelProfile,
    ModelRequest,
    ModelResponse,
    ModelRouteAttempt,
    ModelRouteAttemptOutcome,
    ModelRoutingTrace,
    ModelSensitivity,
    ModelStreamCompleted,
    ModelStreamEvent,
    ModelTextDelta,
    ModelToolCallDelta,
    ModelUsage,
    TextBlock,
    ToolCall,
    ToolDefinition,
    ToolResultBlock,
)
from .protocols import (
    ModelProfileConflictError,
    ModelProfileRepository,
    ModelProfileRepositoryError,
    ModelProvider,
    ModelRouteConflictError,
    ModelRouteRepository,
    ModelRouteRepositoryError,
    StreamingModelProvider,
)
from .providers import (
    AnthropicProvider,
    GeminiProvider,
    GrokProvider,
    OllamaProvider,
    OpenAICompatibleProvider,
    OpenAIProvider,
)
from .routing import (
    ModelProviderRegistration,
    ModelRegistry,
    ModelRoute,
    ModelRouteCandidate,
    ModelRouter,
    RetryPolicy,
    RetryStrategy,
)

__all__ = [
    "AnthropicProvider",
    "CanonicalMessage",
    "FinishReason",
    "GeminiProvider",
    "GrokProvider",
    "MessageRole",
    "ModelProfile",
    "ModelProfileConflictError",
    "ModelProfileRepository",
    "ModelProfileRepositoryError",
    "ModelProvider",
    "ModelProviderError",
    "ModelProviderRegistration",
    "ModelRoute",
    "ModelRouteCandidate",
    "ModelRouteConflictError",
    "ModelRouteRepository",
    "ModelRouteRepositoryError",
    "ModelRegistry",
    "ModelRequest",
    "ModelResponse",
    "ModelRouteAttempt",
    "ModelRouteAttemptOutcome",
    "ModelRouter",
    "ModelRoutingTrace",
    "ModelSensitivity",
    "ModelStreamCompleted",
    "ModelStreamEvent",
    "ModelTextDelta",
    "ModelToolCallDelta",
    "ModelUsage",
    "OllamaProvider",
    "OpenAICompatibleProvider",
    "OpenAIProvider",
    "ProviderErrorCode",
    "RetryPolicy",
    "RetryStrategy",
    "StreamingModelProvider",
    "TextBlock",
    "ToolCall",
    "ToolDefinition",
    "ToolResultBlock",
    "create_llm_provider",
    "create_model_route_provider",
]
