"""Scoped, versioned, provenance-backed portable memory contracts."""

from .learning import (
    RESOURCE_ALIAS_CORRECTION_PREFIX,
    ExplicitCorrectionCatalogReader,
    ExplicitCorrectionCommit,
    ExplicitCorrectionFormatError,
    ExplicitCorrectionLearningError,
    ExplicitCorrectionLearningService,
    ExplicitCorrectionNotEligibleError,
    ExplicitCorrectionResult,
    ExplicitCorrectionStore,
    ExplicitCorrectionStoreConflictError,
    ExplicitCorrectionStoreContractError,
    ResourceAliasCorrection,
)
from .models import (
    MemoryCreator,
    MemoryHistory,
    MemoryInspection,
    MemoryInspectionRequest,
    MemoryKind,
    MemoryListRequest,
    MemoryListResult,
    MemoryProvenance,
    MemoryProvenanceKind,
    MemoryQualification,
    MemoryRecallHit,
    MemoryRecallRequest,
    MemoryRecallResult,
    MemoryRecord,
    MemoryRestoreRequest,
    MemoryScope,
    MemorySensitivity,
    MemorySnapshot,
    MemoryState,
    MemorySupersessionRequest,
    MemoryVersion,
    QualifiedMemory,
    normalize_memory_logical_key,
)
from .protocols import MemoryStore, MemoryStoreConflictError, MemoryStoreError
from .service import MemoryNotFoundError, MemoryService, MemoryServiceContractError

__all__ = [
    "RESOURCE_ALIAS_CORRECTION_PREFIX",
    "ExplicitCorrectionCatalogReader",
    "ExplicitCorrectionCommit",
    "ExplicitCorrectionFormatError",
    "ExplicitCorrectionLearningError",
    "ExplicitCorrectionLearningService",
    "ExplicitCorrectionNotEligibleError",
    "ExplicitCorrectionResult",
    "ExplicitCorrectionStore",
    "ExplicitCorrectionStoreConflictError",
    "ExplicitCorrectionStoreContractError",
    "MemoryCreator",
    "MemoryHistory",
    "MemoryInspection",
    "MemoryInspectionRequest",
    "MemoryKind",
    "MemoryListRequest",
    "MemoryListResult",
    "MemoryNotFoundError",
    "MemoryProvenance",
    "MemoryProvenanceKind",
    "MemoryQualification",
    "MemoryRecallHit",
    "MemoryRecallRequest",
    "MemoryRecallResult",
    "MemoryRecord",
    "MemoryRestoreRequest",
    "MemoryScope",
    "MemorySensitivity",
    "MemoryService",
    "MemoryServiceContractError",
    "MemorySnapshot",
    "MemoryState",
    "MemoryStore",
    "MemoryStoreConflictError",
    "MemoryStoreError",
    "MemorySupersessionRequest",
    "MemoryVersion",
    "QualifiedMemory",
    "ResourceAliasCorrection",
    "normalize_memory_logical_key",
]
